name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./compiler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make clean
      run: make clean
    - name : Install Antrl4
      run: sudo apt install antlr4 libantlr4-runtime-dev default-jdk
    - name: make
      run: make

  tests:
    defaults:
      run:
        working-directory: ./tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: python3 ifcc-test.py testfiles/
