name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./compiler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name : Install Antrl4
      run: sudo apt install antlr4 libantlr4-runtime-dev default-jdk
    - name: Make
      run: make
    - name: Upload compiler
      uses: actions/upload-artifact@master
      with:
        name: compiler
        path: compiler/ifcc

  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests

    outputs:
      files: ${{ steps.test_files.outputs.files }}
        
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve test files
      id: test_files
      run: echo "files=$(find testfiles -type f -name '*.c' | jq -R -cs 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    
  tests:
    runs-on: ubuntu-latest
    needs: [build, setup]
    defaults:
      run:
        working-directory: ./tests
    
    strategy:
      matrix:
        file: ${{ fromJSON(needs.setup.outputs.files) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Download compiler
      uses: actions/download-artifact@master
      with:
        name: compiler
        path: compiler/
        
    - name: Compilation
      id: compile
      continue-on-error: true
      run: |
        base=$(pwd)
        filename=${{ matrix.file }}
        echo "filename=filename" >> $GITHUB_OUTPUT
        
        output_dir="${filename%.c//\//-}"_output
        echo "output_dir=$output_dir" >> $GITHUB_OUTPUT
        mkdir -p "$output_dir"
        cd "$output_dir"
    
        set +e
        gcc -S -o asm-gcc.s $base/$filename > gcc-compile.txt 2>&1 
        gccstatus=$?
        if [ $gccstatus -eq 0 ]; then
            gcc -o exe-gcc asm-gcc.s > gcc-link.txt 2>&1
            gccstatus=$?
        fi
        if [ $gccstatus -eq 0 ]; then
            ./exe-gcc > gcc-execute.txt 2>&1
        fi

        chmod 777 $base/../compiler/ifcc $base/ifcc-wrapper.sh
        $base/ifcc-wrapper.sh asm-ifcc.s "$base/$filename" > ifcc-compile.txt 2>&1
        
        echo "ifccstatus=$?" >> $GITHUB_OUTPUT
        echo "gccstatus=$gccstatus" >> $GITHUB_OUTPUT
        
        echo "Compilation gcc :"
        cat gcc-compile.txt
        echo "-----"
        echo "Compilation ifcc :"
        cat ifcc-compile.txt

    - name: Compare results
      run: |
        cd ${{ steps.compile.outputs.output_dir }}
        
        gccstatus=${{ steps.compile.outputs.gccstatus }}
        ifccstatus=${{ steps.compile.outputs.ifccstatus }}
    
        if [ "$gccstatus" -ne 0 ] && [ "$ifccstatus" -ne 0 ]; then
            echo 'TEST OK'
        elif [ "$gccstatus" -ne 0 ] && [ "$ifccstatus" -eq 0 ]; then
            echo 'TEST FAIL (your compiler accepts an invalid program)'
            exit 1
        elif [ "$gccstatus" -eq 0 ] && [ "$ifccstatus" -ne 0 ]; then
            echo 'TEST FAIL (your compiler rejects a valid program)'
            exit 1
        else
            set +e
            gcc -o exe-ifcc asm-ifcc.s > /dev/null 2>&1 && ./exe-ifcc > ifcc-execute.txt 2>&1
            set -e
        
            echo "Execution gcc :"
            cat gcc-execute.txt
            echo "-----"
            echo "Execution ifcc :"
            cat ifcc-execute.txt
        
            if ! cmp -s "gcc-execute.txt" "ifcc-execute.txt"; then
                echo 'TEST FAIL (different results at execution)'
                exit 1
            else
                echo 'TEST OK'
            fi
        fi
