name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: ./compiler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make clean
      run: make clean
    - name : Install Antrl4
      run: sudo apt install antlr4 libantlr4-runtime-dev default-jdk
    - name: make
      run: make
    - name: debug
      run: tree
    - uses: actions/upload-artifact@master
      with:
        name: compiler
        path: compiler/ifcc

  

  tests:
    defaults:
      run:
        working-directory: ./tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: compiler
        path: compiler/
    - name: Run tests
      run: |
        base=$(pwd)
        for filepath in $(find testfiles -type f -name "*.c"); do
            cd $base

            output_dir="${filepath%.c//\//-}"_output
            mkdir -p "$output_dir" || continue
            cd "$output_dir" || continue
            
            gcc -S -o asm-gcc.s "$filepath" > gcc-compile.txt 2>&1 && gcc -o exe-gcc asm-gcc.s > /dev/null 2>&1 && ./exe-gcc > gcc-execute.txt 2>&1
            gccstatus=$?      

            chmod 777 $base/../compiler/ifcc $base/ifcc-wrapper.sh
            $base/ifcc-wrapper.sh asm-ifcc.s "$base/$filepath" > ifcc-compile.txt 2>&1
            ifccstatus=$?

            echo $(basename $filepath)
            if [ "$gccstatus" -ne 0 ] && [ "$ifccstatus" -ne 0 ]; then
                echo 'TEST OK'
            elif [ "$gccstatus" -ne 0 ] && [ "$ifccstatus" -eq 0 ]; then
                echo 'TEST FAIL (your compiler accepts an invalid program)'
            elif [ "$gccstatus" -eq 0 ] && [ "$ifccstatus" -ne 0 ]; then
                echo 'TEST FAIL (your compiler rejects a valid program)'
            else
                gcc -o exe-ifcc asm-ifcc.s > /dev/null 2>&1 && ./exe-ifcc > ifcc-execute.txt 2>&1
                if ! cmp -s "gcc-execute.txt" "ifcc-execute.txt"; then
                    echo 'TEST FAIL (different results at execution)'
                else
                    echo 'TEST OK'
                fi
            fi
        done
